### ISSUE TITLE
Tunable and Dependent Properties

### ISSUE THREAD

**Issue by renkert2** [renkert2/GraphTools#22]
For dependent properties, what if they are tunable but the dependent property is not? Or vice versa?

If a dependent property is tunable but the properties they depend on are not, then the dependent property will return its own Sym but the parameter it depends on will return a numeric value.  Another way of saying this is that dependencies can currently only flow one way.

**Comment by caksland** [comment]
I fixed this in a commit. Dependent and Tunable cannot be true at the same time. 
We may need to revisit this in the future (I left some comments in the code) because there might be some weird fringe cases that may result in an error.
