### ISSUE TITLE
BUG: Phase.init_vars default calling

### ISSUE THREAD

**Issue by caksland** [renkert2/GraphTools#48]
Phase.init_vars has default naming for state_, control_, and parameter_names. This can cause issues if the arguments are excluded. It might be best to pass things as keywords. 
For example: 

This will throw an error (it'll try to add x to controls, and u and d to inputs.
```
phase.init_vars(openmdao_path="Ctrl", 
                parameter_names=["theta1"],
                output_names = ["y1"],
                })
```

Whereas the following is okay...

```
phase.init_vars(openmdao_path="Ctrl", 
                state_names=[],
                control_names = [],
                parameter_names=["theta1"],
                output_names = ["y1"],
                })
```

**Comment by renkert2** [comment]
Should we just change the default's to empty lists here to avoid any confusion?

**Comment by caksland** [comment]
Yeah. That's what I'm thinking.
