### ISSUE TITLE
BUG: Changing Param Tunable Property throws error on export

### ISSUE THREAD

**Issue by caksland** [renkert2/GraphTools#49]
After building a GraphModel object, a parameter cannot be set to tunable. It throws an error because the parameter is not included in Vars. See psuedocode below.

ex:
```
GM = GraphModel(Graph)
Comp.Param.Tunable = True
GM.init()
m = GM.Convert()
m.export() 
```

**Comment by renkert2** [comment]
Yep.  Last time we talked about this, we thought it made sense to leave Params behind at Graph and switch to SymVars in Model and GraphModel.  Do you think we should try to maintain the link a little longer?

**Comment by caksland** [comment]
Yep. We did do that. But calling GM.init() should completely rebuild the graph model based on the new graph.  In effect, the following are equivalent:
`GM = GraphModel(Graph)
Comp.Param.Tunable = True
GM.init()
m = GM.Convert()
m.export()`

and

`GM = GraphModel(Graph)
Comp.Param.Tunable = True
GM = GraphModel(Graph)
m = GM.Convert()
m.export()`

My guess is that something isn't being updated in Graph when it should be. I can make a TEST file that we can use to debug this issue. I didn't look into this at the time of creating the issue because I had other things to do :/

**Comment by renkert2** [comment]
Sounds good.  I'm taking the afternoon to go after little things like this so I'll check it out.

**Comment by renkert2** [comment]
I Just checked this, and things seem to work well on my end.  The following example code runs great:

```
%% Constructing SystemElements


%% Method 1: Construct with Structure - struct without name field
s = struct();
s.R = 0.01;
s.Kv = 2000;

m = Motor(s);

%% Method 2: Construct with Structure - struct with name field
s(1).Name = "R";
s(1).Value = "0.01";
s(1).Unit = "FakeUnit1";
s(2).Name = "Kv";
s(2).Value = 2000;
s(2).Unit = "FakeUnit2";

m = Motor(s);

%% Method 3: Construct with Name-Value pair arguments
m = Motor("R", 0.01, "Kv", 2000);


%% System Combination
% Params are defined as Constant properties with Parameter property validation
% in the Inverter and Motor components.  

Params = UavParams();
inv = Inverter(Params.inv1);
mot = Motor(Params.mot1);
% Make J Untunable
mot.J.Tunable = false;

% At construction, the components properties are agregated into component.Params
% so the parameters corresponding to a component can be easily modified.
% table(mot.Params)

% The components can be combined into a system just as before.  
ConnectP{1} = [inv.Ports(2) mot.Ports(1)]; % inverter output to motor input
Sys = Combine([inv,mot],ConnectP);

% The parameters of the components being connected are combined into the System's 
% Params property:
% table(Sys.Params)

% The parameters follow the model through the export process.  
% The System graph also has the params at Sys.Graph.Params, as does 
% the model generated by GraphModel

% Build the GraphModel
GM = GraphModel(Sys.Graph);
table(GM.Vars.theta);
disp(symvar(GM.C_sym));

% Make J Tunable
mot.J.Tunable = true;

% Initialize the GraphModel
GM.init()
table(GM.Vars.theta);
disp(symvar(GM.C_sym));

% Convert to Model
M = GM.Convert();
```

**Comment by caksland** [comment]
Oh my gosh. I'm an idiot. In GraphModel.init, there are conditional statements that are `sv.N >1`. That should be `sv.N >0`.
I was running into a fringe case where I had one design parameter and it could opt to create non-design symvars. I'll pull down the branch and push the update.

**Comment by renkert2** [comment]
Gotcha!
