### ISSUE TITLE
Options bug in main_AE

### ISSUE THREAD

**Issue by renkert2** [renkert2/GraphTools#5]
Tried to run main_AE and got this error:
`Error using my_inputparser (line 42)
Provide a valid argument name:
-ReduceDisturbances
-SolveAlgebraics
-AlgebraicOutputs
-PowerflowOutputs
-CapacitanceOutputs

Error in options.GraphModel.GraphOptions (line 15)
                obj = my_inputparser(obj,varargin{:});

Error in graphmodeloptions (line 3)
opts = options.GraphModel.GraphOptions(varargin{:});

Error in main_AE (line 9)
opts = graphmodeloptions('ReduceModel',1,'SolveAlgebraics',0);`

Did you mean to use the 'ReduceDisturbances' option in Line 9 instead of 'ReduceModel'?

**Comment by caksland** [comment]
Yep. I meant Reduce Disturbances. I originally called it ReduceModel, but I realized that could be confusing so I changed it.
Feel free to correct it. Or I can too.
