### ISSUE TITLE
BUG: NanValues in PowerFlowCalculation

### ISSUE THREAD

**Issue by caksland** [renkert2/GraphTools#55]
in CalcP_sym, I was seeing an error for certain combinations of power flow types. eg.
``
P(1) = Type_PowerFlow("xt*xh")
P(2) = Type_PowerFlow("xt/u1")
``
Say Edge 1 has Type P(1) and no input.
Say Edge 2 has Type P(2) and input u(1).
When using the Default CalcPMethod, the vector math calculates each powerflow type for each edge. This is an issue for Edge 1 because Type 2 will be evaluated for Edge 1 with u1= 0. As a result, this returns a NaN value for that Type. When we sum across all types ` P = sum(P,2)`, the result for that edge is a NaN value.

If I recall, this is why there are two CalcPMethods (Method = Edges). Can you confirm?

However, my issue is that if the Default calculation error fails and returns NaN, there is no warning or error. 
Here are a couple ideas:
1) If the Default method returns a NaN, check the coefficient for an (Edge,Type) pair. If the coefficient is a 0, replace the Nan with a 0, else, throw an error.
2) If the Defualt method returns a Nan, re-call the function with the Edges method. If the second call fails, throw an error.
3) When calling the Type method (e.g. `PowerFlowType.calcVal(xt,xh,u)`) the argument `u` is a symbolic array of zeros and syms (e.g. `u1, u2, u3,...`. We could replace the 0 elements with dummy variables (e.g. `z`) so that the calculation does not return a NaN value. The value calculation would still return a 0 if the coefficient for that powerflow type is 0.

Would implementing one of these changes remove the need for the Edges method option.

Another thought. Is if the Default method is even necessary? It's not apparent to me whether the Defuault or Edges method is computationally faster or more scalable. The Default method does vectorize the math operations, but it also ends up computing a lot of unused information because P_coeff is a very sparse matrix. The Edges method does have to individually loop through each edge and type, but it doesn't make any excess calculations. There are pros and cons of each. Have you benchmarked these methods? It could be useful to test the speed of the calculation methods?

**Comment by caksland** [comment]
I've done some testing to compare the Default and Edges methods. The results are extremely clear, the Default method is both faster and more robust to problem size variation. I think the results are interesting so I've shared y methods and results below.

**Setup**
I created a Component called ScalableComp that is passed number of vertices, inputs, edges, and powerflow type information. From this information, it creates a psuedo-random component that meets the specified criteria. In a general sense, ScalableComp is used to test how the calculation methods scale to more complex models. Note, the component limits each edge to have a single PowerFlow type.

**Methods**
In general, I vary the number of vertices, inputs, edges, and types and evaluate the CalcP_sym call time. CalcP_sym is called 11 times, and the results are the average of the last 10 call times (the first call is always slow). Every test case is evaluated for both calculation methods (Default and Edges). I had done some initial testing to see if varying the number of vertices or inputs affected call time, and there was little to no correlation (see the first sheet of CalcPMethodsData.xlsx file if you care about that data). In the results provided below, the following code is used to generate and evaluate the CalcP_sym for variable size models.
```
for i = 20:5:50
    for j = 5:2:15
        comp = ScalableComp('Nv',10,'Nu',10,'Ne',i,'Nt',j);
        SysModel = GraphModel(comp.Graph);
    end
end
```

**Results**
The results are provided in the attached figure. The plots show the Edges, Default, and Edges Fair method. The differences between Edges and Edges Fair methods are
1. Skips creation of P_coeff because it is unused
2. Removes the arrayfun() call because each edge only has a single type.

It should be obvious that in this range of test conditions, the Default method well outperforms the Edges methods. 
- The Default method scales far better for graphs with more edges.  
- The Default method becomes more computationally expensive as a function of the number of types. 
- The number of types does not correlate to the Edges method computation time. This makes sense because the type calculation does not rely on vector math.
- The Fair method provides better results than the Edges method, but is still far worse than the Default method.

Hopefully this is enough proof.
I do want to fix this. I listed some ideas above. Do you have any other ideas?


![image](https://user-images.githubusercontent.com/75496648/154198039-b27f4b8b-68e2-4ea1-aba5-e73e191fdbd8.png)

**Comment by renkert2** [comment]
Dude this is awesome - thanks for doing such an in-depth study. I need to go back through the Default method and re-learn what it’s doing. It would be awesome if it could handle the edge cases that the edge method could. Hopefully it’s a relatively simple fix.

Philip Renkert

________________________________

**Comment by caksland** [comment]
I think I figured out the fix this morning. I still need to test. 
Currently, the Default method loops through each type, and calculates each type value for each edge (e.g. 10 type and 15 edges = 150 values). Each value is then multiplied by it's respective coefficient (many of which are zero). This is all done through vector operations.
Instead of calculating each type value for each edge, we only calculate the type value for edges with non-zero coefficients. This can still be done using vector operations so we should remain computationally efficient.
I'll look into this today.

Is it possible to go back through a commit history and see when the Edges method was introduced. Maybe there will be an example file?

**Comment by caksland** [comment]
Here's an update to my previous posts.
I tested the new method proposed above and have provided the results below. The New method still outperforms the Edges method.
In comparison to the Default method, the New method is worse for small problem sizes, but scales better for larger problems. If you compare the Default and New method codes, I have no clue why the New method performs worse at small scales. I guess sub-indexing vectors increases computation expense? At one point, I tested a coding variation of the New Method (see below) that had longer computation time for ALL test cases... I don't really see why one would be faster than the other. Note that ``obj.P_coeff_NonZero`` was created outside the ``tic...toc`` calls.

_I'm going to remove the Default and Edges methods from the tool. I don't think there is any need for them at this point. Do you agree._

Default Method Code:
```
        P = sym(zeros(size(p_coeff)));
        for i = 1:size(p_coeff,2)
            P(:,i) = p_coeff(:,i).*obj.PType(i).calcVal(xt,xh,u);
        end
```
New Method Code:
```
        NonZeroIdx = obj.P_coeff_NonZero; 
        P = sym(zeros(size(p_coeff)));
        for i = 1:size(p_coeff,2)
            edgeIdx = NonZeroIdx(:,i);
            P(edgeIdx,i) = p_coeff(edgeIdx,i).*obj.PType(i).calcVal(xt(edgeIdx),xh(edgeIdx),u(edgeIdx,:));
        end
```

New Method Code Variation
```
        NonZeroIdx = obj.P_coeff_NonZero; 
        P = sym(zeros(size(p_coeff)));
        for i = 1:size(p_coeff,2)
            edgeIdx = NonZeroIdx(:,i);
            edgeVal = obj.PType(i).calcVal(xt(edgeIdx),xh(edgeIdx),u(edgeIdx,:));
            P(edgeIdx,i) = p_coeff(edgeIdx,i).*edgeVal;
        end
```

![image](https://user-images.githubusercontent.com/75496648/154341615-124e5138-f655-4b94-ba0a-7b515960946e.png)

**Comment by renkert2** [comment]
Sounds good!  Would be good to keep them archived somewhere just in case.

Philip Renkert

________________________________

**Comment by caksland** [comment]
I will add a file call Archived CalcP_sym...
