### ISSUE TITLE
FEATURE: Faster flattenJac call

### ISSUE THREAD

**Issue by caksland** [renkert2/GraphTools#64]
In the model export process, the line valCon=double(J(idxCon)) (see flattenJac in ModelFunction) is approximately 90% of the total model export line. The function call converts symbolic constant values to doubles and allows us to differentiate between 0 elements and nonzero constant elements in the jacobian. This was a function call that I could not find a more efficient computation method for. I now have two ideas to speed this up.
1) Convert the symbolic expressions to strings using the sprintf function (I use this elsewhere the the model export code) and compare the string values to a zero string (e.g. strcmp(J_str(idxCon), "0"). I believe converting syms to strings can be more efficient than converting syms to doubles. This may not be a significant improvement because I think sprintf is still relatively slow for large symbolic arrays... That's why we opted to specify sparsity in the first place. 
2) For models derived from Graphs, we can leverage the graph sparsity. The adjacency matrix of the graph (A=M*M^T) will tell us which values are 0 and which values are not. Additionally, if we know the jacobian of the individual powerflows, we can detect which pieces of the total jacobian are non-zero constant... This may require a rework of GraphModel...

This can possibly be done in conjuction with the following issues. #15 #13

EDIT: The call to hasSymType is also really slow... It's actually slower than the call to double.

**Comment by caksland** [comment]
I briefly investigated method 1. I learned a couple things.
1. Using char to convert sym to strings is pretty fast. Faster than sprintf. The difference is that the output character array is formatted funny. It may be easy and fast to fix that though...
2. Method two is ~3-6 times faster than directly calling double. The only issue is that valConstant ( represents the constant nonzero values in the jacobian) is a string and not a double... this messes with the metadata output. calling double(valConstant) is too slow. Maybe phil has some ideas.
```
                tic              
                strCon = char(J(idxCon));
                strCon = split(strCon(10:end-3),'], ['); % split is faster than strsplit. indexing required to fix formatting 
                idxZero = strcmp(strCon,"0");
                rowsConst(idxZero) = [];
                colsConst(idxZero) = [];
                valConst = strCon(~idxZero);
                toc
```

**Comment by renkert2** [comment]
Could you try the str2num function:
```
valConst = str2num(valConst)
``` 
If valConst is a char array, calling double on it seems to return the ASCII characters of the number instead of the number itself.

**Comment by caksland** [comment]
I ended up using str2num. It calls eval but it was the best and fastest method I could find.
I'm working on a large overhaul to the export information on MDAO modeling at the moment so you can see how everything works then. For one of my UAV systems, the export time decreased from ~4.5s to ~.66s. It's pretty well optimized.

I did try text replacement, but that did not work. It was really fast, but some of the constant values may by 21/38 for example. When the .json file is read by python, I was receiving an error "unknown delimiter". maybe there is a way around that? But I figured the time save is marginal (.02s).
